### ISSUE TITLE
Ability to set combo font

### ISSUE THREAD

**Issue by Clpsplug** [JoelBesada/activate-power-mode#199]
This plugin has got a combo display which is awesome, but when I toggled that on the font was not what it looked like on README.
Since I don't have that awesome NES font on my computer, (☹️) it looks like atom used the system default font.
I did a quick search on the repo but did not see any value for setting the combo font. Could you:

* put a feature to set the combo font (I have some awesome fonts I want to try out)
  * if that's difficult maybe tell me what lines should I add to the CSS? I'm not afraid of that.
* tell me what font is used in README.md if possible?

**Comment by lexcast** [comment]
Someone else is having this issue?
The font is packaged with the plugin 😕. You can see it on the `fonts/` folder.

To change the font, open the command palette and search for `Application: Open Your Stylesheet`, then put something like:
```less
atom-text-editor::shadow .streak-container,
.streak-container {
  font-family: sans-serif; // your font
}
```
