### ISSUE TITLE
Editor lags with shake enabled.

### ISSUE THREAD

**Issue by Costinutz32** [JoelBesada/activate-power-mode#203]
On a 400 line index page, there are constant lags with the shake effect enabled. Leaving only particles enabled works just fine, but this ruins the purpose of the plugin.

System : Intel NUC 6i5 ( i5 6260U / Intel Iris 540 / 16GB DDR4 / 512 PCIE SSD )
Also, the cpu usage jumps to 60-70 when the shake effect occurs ( and Atom using 35-45% )
Thanks!

**Comment by lexcast** [comment]
try inserting in your stylesheet the following:
```less
atom-text-editor::shadow,
atom-text-editor {
  transform: translate3d(0,0,0);
}
```

**Comment by marcoms** [comment]
Using the new `will-change` property might be better. https://developer.mozilla.org/en/docs/Web/CSS/will-change

```css
atom-text-editor {
    will-change: transform;
}
```

**Comment by lexcast** [comment]
perhaps with this? top and left properties are what really changes on screen shake 
```css
atom-text-editor,
atom-text-editor::shadow {
    will-change: top, left;
}
```
