### ISSUE TITLE
Show combo counter only when it reaches activation threshold

### ISSUE THREAD

**Issue by JuanQP** [JoelBesada/activate-power-mode#230]
I was thinking it would be more great if the combo counter was not visible by default. And then, when it reaches the activation threshold, shows itself.

**Comment by lexcast** [comment]
paste this on your styles.less file:
```less
atom-text-editor::shadow .streak-container {
  display: none;

  &.reached {
    display: block;
  }
}
```
