### ISSUE TITLE
Hide counter while remains in 0

### ISSUE THREAD

**Issue by RodrigoHamuy** [JoelBesada/activate-power-mode#239]
Just that, is super fun to have this when writing but is annoying when you are just reading.

**Comment by lexcast** [comment]
fixed on #254 
in your styles.less paste the following:
```css
atom-text-editor .streak-container.combo-zero {
   display: none;
}
```
