### ISSUE TITLE
How can I get current streak count?

### ISSUE THREAD

**Issue by Jerajo** [JoelBesada/activate-power-mode#287]
Hello @lexcast.

I use the **[API](https://github.com/JoelBesada/activate-power-mode/wiki/Api)** `getCombo()` but it doesn't return me the current streak count, I only get the current level with `getLevel()`, It should be also a way to get the current streak count.

Here is here is the code I used.
```
onComboStartStreak: () ->
    console.log "I got this: " + @api.getCombo() + " == " + @getConfig "activationThreshold"
    if @api.getCombo() >= @getConfig "activationThreshold"
      @musicPlayer.play @api.getCombo()
```

Output:
    `I got this: [object Object] == 1`

I would like to get this.
   `I got this: 1 == 1`

**How can I do this?** Or I will need to include the function `getStreak()` inside the api code.

**Comment by lexcast** [comment]
Hi @Jerajo 
You are right, there is no way to get the current streak.
If you submit a PR with that function would be great :smile:

**Comment by Jerajo** [comment]
Thanks for the quick answer @lexcast I'm working on it.

Other thing that I realice is that activation threshold doesn't apear on settings.

```
activationThreshold:
        title: "Combo Mode - Activation Threshold"
        description: "Streak threshold to activate the power mode."
        type: "array"
        default: [20, 50, 100, 200, 500]
        items:
          type: "integer"
          minimum: 1
          maximum: 1000
```

I remember that before I can select 1 for activation threshold, but now it always start on 20.
I thing that the error is cause for the default value. It only needs to be `default: 20`
